apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: triliumnext/trilium:v0.101.3
          ports:
            - containerPort: 8080
          env:
            - name: TRILIUM_DATA_DIR
              value: /home/node/trilium-data
          volumeMounts:
            - name: data-volume
              mountPath: /home/node/trilium-data
              readOnly: false
            - name: tz-config
              mountPath: /etc/timezone
              readOnly: true
            - name: lt-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: trilium-data-pvc
        - name: tz-config
          hostPath:
            path: /etc/timezone
            type: File
        - name: lt-config
          hostPath:
            path: /etc/localtime
            type: File