apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trilium-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - trlm.xyz.abc
      secretName: homelab-tls
  rules:
    - host: trlm.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trilium-service
                port:
                  number: 8080