apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliumwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triliumwork
  template:
    metadata:
      labels:
        app: triliumwork
    spec:
      containers:
        - name: triliumwork
          image: triliumnext/trilium:v0.101.3
          ports:
            - containerPort: 8080
          env:
            - name: TRILIUM_DATA_DIR
              value: /home/node/trilium-data
          volumeMounts:
            - name: data-volume
              mountPath: /home/node/trilium-data
              readOnly: false
            - name: tz-config
              mountPath: /etc/timezone
              readOnly: true
            - name: lt-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: triliumwork-data-pvc
        - name: tz-config
          hostPath:
            path: /etc/timezone
            type: File
        - name: lt-config
          hostPath:
            path: /etc/localtime
            type: File