apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazanoke
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mazanoke
  template:
    metadata:
      labels:
        app: mazanoke
    spec:
      containers:
        - name: mazanoke
          image: ghcr.io/civilblur/mazanoke:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80