# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codearm
spec:
  replicas: 0
  selector:
    matchLabels:
      app: codearm
  template:
    metadata:
      labels:
        app: codearm
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: codearm
          image: linuxserver/openvscode-server:1.109.5
          ports:
            - containerPort: 3000
          env:
            - name: PROXY_DOMAIN
              value: codearm.xyz.abc
            - name: DEFAULT_WORKSPACE
              value: /workspace
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Asia/Manila
            - name: SUDO_PASSWORD
              value: 'passme!ng@est'
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: false
            - name: workspace-volume
              mountPath: /workspace
              readOnly: false
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: codearm-config-pvc
        - name: workspace-volume
          persistentVolumeClaim:
            claimName: codearm-workspace-pvc