apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: CHANGEME-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: CHANGEME.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: CHANGEME-service
                port:
                  number: CHANGEPORT